## geometry
geometry.prob_lo = [-0.5, -0.5, -0.5]
geometry.prob_hi = [0.5, 0.5, 0.5]
quokka.bc = ["periodic", "periodic", "periodic"]

## resolution
amr.n_cell = [1024, 1024, 8]
amr.max_level = 0
amr.max_grid_size = 1024
amr.blocking_factor_x = 1024
amr.blocking_factor_y = 1024
amr.blocking_factor_z = 8

## verbosity
amr.v = 1

## output
checkpoint_interval = -1
plotfile_interval = 4000
plotfile_prefix = "snapshots/plt"

## time integration
cfl = 0.2
stop_time = 1.0
max_timesteps = 100000

## hydro
hydro.rk_integrator_order = 2
hydro.reconstruction_order = 5

## mhd
mhd.emf_compute_scheme = "FelkerStone2017"
mhd.emf_averaging_scheme = "LondrilloDelZanna2004"
mhd.emf_reconstruction_order = 5
