## geometry
geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [1.0, 1.0, 1.0]
quokka.bc = ["periodic", "periodic", "periodic"]

## verbosity
amr.v = 0

## output
checkpoint_interval = -1
plottime_interval = -1

## time integration
cfl = 0.3

## hydro
hydro.rk_integrator_order = 2
hydro.reconstruction_order = 2

## mhd
mhd.emf_compute_scheme = "Balsara2025"
mhd.emf_averaging_scheme = "LondrilloDelZanna2004"
mhd.emf_reconstruction_order = 2

## problem setup
setup.angle_between_k_b0 = 90.0
setup.machine_precision_target = 0
setup.num_modes_x = 1
setup.num_modes_y = 0
setup.num_modes_z = 0
setup.nx_max = 2048
