## geometry
geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [1.0, 1.0, 1.0]
quokka.bc = ["periodic", "periodic", "periodic"]

## resolution
amr.n_cell = [128, 8, 8]
amr.max_level = 0
amr.max_grid_size = 128
amr.blocking_factor_x = 128
amr.blocking_factor_y = 8
amr.blocking_factor_z = 8

## verbosity
amr.v = 0

## output
checkpoint_interval = -1
plottime_interval = -1

## time integration
cfl = 0.3
stop_time = 1.0

## hydro
hydro.rk_integrator_order = 2
hydro.reconstruction_order = 5

## mhd
mhd.emf_compute_scheme = "FelkerStone2017"
mhd.emf_averaging_scheme = "LondrilloDelZanna2004"
mhd.emf_reconstruction_order = 5
mhd.resistivity = 0.01

## problem setup
setup.angle_between_k_b0 = 0
setup.num_modes_x = 1
setup.num_modes_y = 0
setup.num_modes_z = 0
